app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:index

admin:
    path: /admin
    defaults:
        _controller: AppBundle:Admin:index

hlasenia_pm:
    path: /hlasenia-pm
    defaults:
        _controller: AppBundle:HlaseniaPM:show

ris-servisne-hlasenia:
    path: /ris/sh
    defaults:
        _controller: AppBundle:ServisneHlasenia:index

denny-plan-prevadzky:
    path: /ee/dpp
    defaults:
        _controller: AppBundle:DennyPlanPrevadzky:index

sczt-vychod:
    path: /disp/scztv
    options:
        expose: true
    defaults:
        _controller: AppBundle:SCZTVychod:index

dodavka-zdrojov:
    path: /disp/dz
    defaults:
        _controller: AppBundle:DodavkaZdrojov:index

vykon-ost:
    path: /disp/vko
    defaults:
        _controller: AppBundle:VykonOST:index

vychladenie-ost:
    path: /disp/vco
    options:
        expose: true
    defaults:
        _controller: AppBundle:VychladenieOST:index

skutocna-cena-tepla:
    path: /kont/sct
    options:
        expose: true
    defaults:
        _controller: AppBundle:SkutocnaCenaTepla:index