app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:index

admin:
    path: /admin
    defaults:
        _controller: AppBundle:Admin:index

hlasenia_pm:
    path: /hlasenia-pm
    defaults:
        _controller: AppBundle:HlaseniaPM:show

analyzy-notifikacie-merani:
    path: /smo/anm
    options:
        expose: true
    defaults:
        _controller: AppBundle:AnalyzyNotifikacieMerani:index

report-meracov:
    path: /smo/rm
    options:
        expose: true
    defaults:
        _controller: AppBundle:ReportMeracov:index

ris-servisne-hlasenia:
    path: /ris/sh
    defaults:
        _controller: AppBundle:ServisneHlasenia:index

denny-plan-prevadzky:
    path: /ee/dpp
    options:
        expose: true
    defaults:
        _controller: AppBundle:DennyPlanPrevadzky:index

sczt-vychod:
    path: /disp/scztv
    options:
        expose: true
    defaults:
        _controller: AppBundle:SCZTVychod:index

sczt-zapad:
    path: /disp/scztz
    options:
        expose: true
    defaults:
        _controller: AppBundle:SCZTZapad:index

sczt-ost:
    path: /disp/scztost
    options:
        expose: true
    defaults:
        _controller: AppBundle:SCZTOST:index

vychladenie-ost:
    path: /disp/vco
    options:
        expose: true
    defaults:
        _controller: AppBundle:VychladenieOST:index

miestne-prevadzkove-predpisy-tpv:
    path: /prev/mpp-tpv
    options:
        expose: true
    defaults:
        _controller: AppBundle:MiestnePrevadzkovePredpisyTpV:index

miestne-prevadzkove-predpisy-tpz:
    path: /prev/mpp-tpz
    options:
        expose: true
    defaults:
        _controller: AppBundle:MiestnePrevadzkovePredpisyTpZ:index

miestne-prevadzkove-predpisy-vhj:
    path: /prev/mpp-vhj
    options:
        expose: true
    defaults:
        _controller: AppBundle:MiestnePrevadzkovePredpisyVhJ:index

skutocna-cena-tepla:
    path: /kont/sct
    options:
        expose: true
    defaults:
        _controller: AppBundle:SkutocnaCenaTepla:index

vyhodnotenie-ceny-tepla:
    path: /kont/vct
    options:
        expose: true
    defaults:
        _controller: AppBundle:VyhodnotenieCenyTepla:index

danove-priznanie:
    path: /uct/dp
    options:
        expose: true
    defaults:
        _controller: AppBundle:DanovePriznanie:index

projekty:
    path: /projekty
    options:
        expose: true
    defaults:
        _controller: AppBundle:Projekty:index