# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/3.4/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db_provider:
            entity:
                class: AppBundle:App\User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #anonymous: ~
            # activate different ways to authenticate

            provider: db_provider

            remote_user:
                provider: db_provider

            logout_on_user_change: true

    access_control:
        - { path: ^/hlasenia-pm, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:     [ROLE_VIP, ROLE_NCT, ROLE_SCT, ROLE_VCT, ROLE_DPP, ROLE_DP_UCT, ROLE_ANM, ROLE_MPP_TPV, ROLE_MPP_TPZ, ROLE_MPP_VHJ]
        ROLE_NCT:       [ROLE_NCT_ADMIN]
        ROLE_NCT_ADMIN: [ROLE_NCT_KONT]
        ROLE_NCT_KONT:  [ROLE_NCT_MNG]
        ROLE_SCT:       [ROLE_SCT_ADMIN]
        ROLE_SCT_ADMIN: [ROLE_SCT_KONT]
        ROLE_SCT_KONT:  [ROLE_SCT_MNG]
        ROLE_SCT_MNG:   [ROLE_SCT_VYR]
        ROLE_VCT:       [ROLE_VCT_ADMIN]
        ROLE_VCT_ADMIN: [ROLE_VCT_KONT]
        ROLE_VCT_KONT:  [ROLE_VCT_MNG]
        ROLE_DP_SUPER:  [ROLE_DP_UCT]
